package com.example.dblib.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dblib.entity.AppConfig;

import com.example.dblib.greendao.AppConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appConfigDaoConfig;

    private final AppConfigDao appConfigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appConfigDaoConfig = daoConfigMap.get(AppConfigDao.class).clone();
        appConfigDaoConfig.initIdentityScope(type);

        appConfigDao = new AppConfigDao(appConfigDaoConfig, this);

        registerDao(AppConfig.class, appConfigDao);
    }
    
    public void clear() {
        appConfigDaoConfig.clearIdentityScope();
    }

    public AppConfigDao getAppConfigDao() {
        return appConfigDao;
    }

}
